---
- name: create destination directory
  file:
    dest: "{{ service_destination_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: place docker-compose files
  copy:
    src: "{{ item }}"
    dest: "{{ service_destination_dir }}"
    owner: root
    group: root
    mode: 0760
  with_fileglob:
    - "{{ service_repository_root }}/docker-compose.yml"
    - "{{ service_repository_root }}/docker-compose.*.yml"

- name: place docker env files
  copy:
    src: "{{ item }}"
    dest: "{{ service_destination_dir }}"
    owner: root
    group: root
    mode: 0760
  with_fileglob:
    - "{{ service_repository_root }}/{{ env_file }}"

- name: docker-compose pull
  command: docker-compose pull
  args:
    chdir: "{{ service_destination_dir }}"

- name: docker-compose up
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ service_destination_dir }}"
