---
- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  always_run: yes


- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present
  always_run: yes


- name: register kernel version
  command: "uname -r"
  register: kernel_version


- name: install prereqs and docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - "linux-image-extra-{{ kernel_version.stdout }}"
    - linux-image-extra-virtual
    - docker-engine


- name: Install pip, python-dev package with apt
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - python-dev
    - python-pip
  always_run: yes


- name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: pip, version: "{{ pip_version_pip }}" }
    - { name: setuptools, version: "{{ pip_version_setuptools }}" }
    - { name: docker, version: "{{ pip_version_docker }}" }
    - { name: docker-compose, version: "{{ pip_version_docker_compose }}" }


- name: add docker group
  group:
    name: docker
    state: present


- name: place docker config
  template:
    src: docker.default.j2
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0644
  notify:
    - restart docker
  tags:
    - docker_config

- name: docker login
  shell: "docker login -e {{ docker_email }} -p {{ docker_pwd }} -u {{ docker_username }}"
  become: yes
